### ISSUE TITLE
Замечания по заданию Car (lw.3)

### ISSUE THREAD

**Issue by iandreyshev** [AlekseyMinai/lab01#6]
- [x] Именование приватных полей должно отличаться от именования публичных полей и аргументов методов.
```kt
private var isSwitchedOn = false
private var movementState = MovementState.STAND
private var speed: Int = 0
private var gear: Int = 0
```
- [x] Название переменной слишком общее
```kt
private var isSwitchedOn = false
```

**Comment by iandreyshev** [comment]
- [x] Нет смысла хранить диапазоны скоростей передач в одном массиве для всего набора передач. Путает, что в элементе 0 лежит передача для реверса, Стоит использовать для Map. Передачи можно вынести в константы

**Comment by iandreyshev** [comment]
- [x] Класс автомобиля не должен отвечать за вывод информации, он может иметь публичные поля для того, чтобы клиентский код мог узнать состояние двигателя, скорости и т.д. и вывести информационное сообщение про изменение состояние автомобиля.
- [x] Автомобиль не должен уметь печатать полную информацию о себе, этим должен заниматься клиентский код.

**Comment by iandreyshev** [comment]
- [x] В тестах проверка изменения состояния должна происходить не с помощью результата функций setGear, turnOnEngine и т.д. , а с помощью проверки состояния автомобиля с ожидаемыми значениями. Для этого интерфейс автомобиля должен предоставлять клиентскому коду публичные поля. Это связанно с замечанием выше, т.к. там тоже упоминаются публичные поля состояния автомобиля.

Например, после переключения передачи в тестах нужно получить текущую передачу автомобиля и сверить её с ожидаемым значением

**Comment by iandreyshev** [comment]
- [ ] Программа должна считывать параметры через пробел

**Comment by iandreyshev** [comment]
**Коэффициент - 0.6**

**Comment by AlekseyMinai** [comment]
> * через пробел

два раза перечитал не нашел такого требования..

**Comment by alexeyminay** [comment]
> * [ ]  Программа должна считывать параметры через пробел

два раза перечитал не нашел такого требования..

**Comment by iandreyshev** [comment]
> > * [ ]   Программа должна считывать параметры через пробел
> 
> два раза перечитал не нашел такого требования..

Хорошо. А почему решено сделать через нижнее подчеркивание? Просто во всех других программах делал через пробел и это является общепринятым подходом.

**Comment by iandreyshev** [comment]
**Коэффициент - 1**
