### ISSUE TITLE
Замечания по заданию Vector (lw.2, op.1)

### ISSUE THREAD

**Issue by iandreyshev** [AlekseyMinai/lab01#8]
- [x] По заданию нужно прибавить к каждому элементу массива среднее арифметическое его положительных элементов. Сейчас программа прибавляет ко всем элементам среднее арифметическое всех элементов.
- [x] Можно избавиться от создания floatList и splittedString, используя функцию-расширение mapNotNull к списку полученному после разделения строки
Было:
```kt
fun String.toDoubleList(): List<Double> {
    val splittedString = this.split(" ")
    val floatList = mutableListOf<Double>()
    splittedString.forEach {
        try {
            floatList.add(it.toDouble())
        } catch (e: NumberFormatException) {
            print("\"$it\" - не число \n")
        }
    }
    return floatList
}
```
Стало:
```kt
fun String.toDoubleList(): List<Double> =
        split(" ").mapNotNull {
            TODO()
        }
```
- [x] doubleList -> listOfDouble
- [x] toDoubleList -> toListOfDouble
- [x] По названию теста appCase не понятно, что в нем проверяется

**Comment by iandreyshev** [comment]
**Коэффициент - 0.2**
**Доп за распознавание слов в разном регистре - 10**

**Comment by iandreyshev** [comment]
**Вопросы**
* Название функции readIn (Читать в) не отображает, что в ней действительно происходит, подразумевалось Read input? Видимо, это было взято из названий класса System.

**Comment by alexeyminay** [comment]
> **Вопросы**
> 
> * Название функции readIn (Читать в) не отображает, что в ней действительно происходит, подразумевалось Read input? Видимо, это было взято из названий класса System.

так и есть. Исправил на readInput

**Comment by iandreyshev** [comment]
**Коэффициент - 1**
